import streamlit as st
import json
import os
import google.generativeai as genai

st.set_page_config(page_title="Ontology Wars: Epic Chronicles", page_icon="⚔️", layout="wide")
st.title("⚔️ Ontology Wars: Epic Chronicles")
st.markdown("### Semantic Web-driven strategy simulation chronicles")

st.sidebar.header("Configuration")
api_key = st.sidebar.text_input("Gemini API Key", type="password")
story_lang = st.sidebar.selectbox("Story Language", ["English", "Türkçe"])

if not api_key:
    st.info("👈 Please enter your Gemini API Key in the sidebar to proceed.")
    st.stop()

genai.configure(api_key=api_key)
model = genai.GenerativeModel('gemini-2.5-flash')

def load_telemetry():
    if os.path.exists("telemetry_log.json"):
        with open("telemetry_log.json", "r", encoding="utf-8") as f:
            return json.load(f)
    return None

log_data = load_telemetry()

if log_data:
    st.success("Knowledge Graph logs loaded successfully.")
    
    total_turns = len(log_data)
    selected_turn = st.slider("Select Turn", 1, total_turns, 1)
    turn_info = log_data[selected_turn - 1]
    
    col1, col2 = st.columns([1, 2])
    
    with col1:
        st.subheader(f"📊 Turn {selected_turn} Data (A-Box)")
        st.json(turn_info)
        
    with col2:
        st.subheader("📜 The Chronicler's Tale")
        if st.button("Generate Tale"):
            lang_instruction = "Write the story entirely in English." if story_lang == "English" else "Hikayeyi tamamen Türkce fantastik bir roman diliyle yaz."
            
            prompt = f"""
            You are a master fantasy novelist. Transform the following strategy game turn data into an immersive, epic, and dramatic chapter of a novel. 
            The data is generated by an OWL-based Semantic Web reasoning engine. 
            Focus on the political tension, wars, alliances, and resource crises (like famine).
            Use expressive language, dramatic pacing, and relevant emojis to enhance the reading experience. 
            Keep it engaging but concise (around 2-3 paragraphs).
            {lang_instruction}
            
            Turn Data: {json.dumps(turn_info)}
            """
            
            with st.spinner("The Chronicler is writing..."):
                try:
                    response = model.generate_content(prompt)
                    st.write(response.text)
                except Exception as e:
                    st.error(f"API Error: {e}")
else:
    st.error("Log file not found. Please run the engine to generate telemetry_log.json.")